version: '3.9'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: teste_tecnico
    networks:
      - teste_tecnico_sp1

networks:
  teste_tecnico_sp1:
    