version: '3.9'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
      
    networks:
      - teste_tecnico_sp1
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - .env
    networks:
      - teste_tecnico_sp1
networks:
  teste_tecnico_sp1:
